"""Export the physics rule (no ML) for an MCU (ESP32) and verify the reference implementation against the feature code used in training.
Rule (50 Hz):  impact k = sample with |acc| >= 1.6 g that is the maximum within +-49 samples;  1.3 s later compute
   tilt = angle( mean(acc[k-50 .. k-26]) , mean(acc[k+15 .. k+64]) )     (pre-impact gravity vs gravity 0.3..1.3 s after)
   FALL if tilt >= 40 deg."""
import json, os, glob
import numpy as np, pandas as pd
from .features import extract, ang

HERE = os.path.dirname(os.path.abspath(__file__))
PARAMS = dict(fs_hz=50, impact_peak_g=1.6, impact_max_window_samples=49, pre_mean_from=-50, pre_mean_to=-26, post_mean_from=15, post_mean_to=64, tilt_deg=40.0, ml_gate_tilt_deg=5.0,
              alert_delay_samples=65, note="alert can be raised 1.3 s after the impact (rule only); the ML tier needs 2.0 s")
json.dump(PARAMS, open(os.path.join(HERE, "rule_params.json"), "w"), indent=2)

HEADER = r'''// fall_rule_params.h  -- auto-generated by fall_detector/export_rule.py (physics rule, no ML, 50 Hz accelerometer)
#pragma once
#include <math.h>
#define FALL_FS_HZ            50
#define FALL_IMPACT_G         1.6f     // |acc| trigger
#define FALL_PEAK_HALF_WIN    49       // trigger must be the max within +-49 samples
#define FALL_PRE_FROM        (-50)     // pre-impact gravity = mean over [k-50, k-26]
#define FALL_PRE_TO          (-26)
#define FALL_POST_FROM        15       // post gravity = mean over [k+15, k+64]  (0.3 .. 1.3 s)
#define FALL_POST_TO          64
#define FALL_TILT_DEG         40.0f    // FALL if the posture change >= 40 deg
// acc[i][0..2] in g, linear buffer containing at least samples k-50 .. k+64. Returns the posture change in degrees.
static inline float fall_tilt_deg(const float acc[][3], int k) {
    float p[3] = {0,0,0}, q[3] = {0,0,0}; int np_ = 0, nq = 0;
    for (int i = k + FALL_PRE_FROM;  i <= k + FALL_PRE_TO;  ++i) { for (int c = 0; c < 3; ++c) p[c] += acc[i][c]; ++np_; }
    for (int i = k + FALL_POST_FROM; i <= k + FALL_POST_TO; ++i) { for (int c = 0; c < 3; ++c) q[c] += acc[i][c]; ++nq; }
    float dot = 0, np2 = 0, nq2 = 0;
    for (int c = 0; c < 3; ++c) { p[c] /= np_; q[c] /= nq; dot += p[c]*q[c]; np2 += p[c]*p[c]; nq2 += q[c]*q[c]; }
    float cs = dot / (sqrtf(np2) * sqrtf(nq2) + 1e-9f); if (cs > 1) cs = 1; if (cs < -1) cs = -1;
    return acosf(cs) * 57.2957795f;
}
'''
open(os.path.join(HERE, "fall_rule_params.h"), "w").write(HEADER)


def tilt_reference(a, k):
    p = a[k + PARAMS["pre_mean_from"]:k + PARAMS["pre_mean_to"] + 1].mean(0); q = a[k + PARAMS["post_mean_from"]:k + PARAMS["post_mean_to"] + 1].mean(0)
    return ang(p, q)


if __name__ == "__main__":
    from scipy.signal import find_peaks
    errs, n = [], 0
    for p in sorted(glob.glob(r"C:\Users\Admin\Desktop\IMU_data\danh_gia\fall_data_crop5s\person*\*.csv"))[:40] + sorted(glob.glob(r"C:\Users\Admin\Desktop\IMU_data\danh_gia\data_normal\running_person3*.csv"))[:2]:
        d = pd.read_csv(p); a = d[["accX_g", "accY_g", "accZ_g"]].values; g = d[["gyrX_dps", "gyrY_dps", "gyrZ_dps"]].values
        pk, _ = find_peaks(np.linalg.norm(a, axis=1), height=1.6, distance=50)
        for k in pk:
            if k < 50 or k + 100 > len(a): continue
            lo, hi = max(0, k - 50), min(len(a), k + 101); ref = extract(a[lo:hi], g[lo:hi], 50.0, k - lo)["O_tilt_A"]
            errs.append(abs(ref - tilt_reference(a, k))); n += 1
    print(f"exported rule_params.json + fall_rule_params.h | reference-vs-training tilt_A on {n} events: max abs error {max(errs):.6f} deg")
