// fall_rule_params.h  -- auto-generated by fall_detector/export_rule.py (physics rule, no ML, 50 Hz accelerometer)
#pragma once
#include <math.h>
#define FALL_FS_HZ            50
#define FALL_IMPACT_G         1.6f     // |acc| trigger
#define FALL_PEAK_HALF_WIN    49       // trigger must be the max within +-49 samples
#define FALL_PRE_FROM        (-50)     // pre-impact gravity = mean over [k-50, k-26]
#define FALL_PRE_TO          (-26)
#define FALL_POST_FROM        15       // post gravity = mean over [k+15, k+64]  (0.3 .. 1.3 s)
#define FALL_POST_TO          64
#define FALL_TILT_DEG         40.0f    // FALL if the posture change >= 40 deg
// acc[i][0..2] in g, linear buffer containing at least samples k-50 .. k+64. Returns the posture change in degrees.
static inline float fall_tilt_deg(const float acc[][3], int k) {
    float p[3] = {0,0,0}, q[3] = {0,0,0}; int np_ = 0, nq = 0;
    for (int i = k + FALL_PRE_FROM;  i <= k + FALL_PRE_TO;  ++i) { for (int c = 0; c < 3; ++c) p[c] += acc[i][c]; ++np_; }
    for (int i = k + FALL_POST_FROM; i <= k + FALL_POST_TO; ++i) { for (int c = 0; c < 3; ++c) q[c] += acc[i][c]; ++nq; }
    float dot = 0, np2 = 0, nq2 = 0;
    for (int c = 0; c < 3; ++c) { p[c] /= np_; q[c] /= nq; dot += p[c]*q[c]; np2 += p[c]*p[c]; nq2 += q[c]*q[c]; }
    float cs = dot / (sqrtf(np2) * sqrtf(nq2) + 1e-9f); if (cs > 1) cs = 1; if (cs < -1) cs = -1;
    return acosf(cs) * 57.2957795f;
}
