; ESP32-S3 + 10DOF (ADXL345 +-2 g, ITG3200, QMC5883L) + Pulse sensor, TinyFallNet on-device fall detection
[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_mode = dio
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = default.csv
board_build.arduino.memory_type = dio_qspi
monitor_speed = 115200
upload_speed = 115200
build_flags =
    -O2
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.2
