"""Export a trained TinyFallNet to plain C (float32, no library) for the ESP32-S3.
 - BatchNorm folded into the convolutions, dropout removed.
 - Writes esp32/fall_cnn_weights.h (+ a self-test window and its expected score).
 - Checks a numpy re-implementation that follows the C loops line by line against PyTorch."""
import os, sys, numpy as np, torch
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
from model import TinyFallNet, front

OUT = os.path.join(HERE, "esp32"); os.makedirs(OUT, exist_ok=True)


def fold(seq):
    """Sequential(Conv1d(bias=False), BN, ReLU) -> (W[o][i/g][k], b[o])"""
    c, bn = seq[0], seq[1]
    s = (bn.weight / torch.sqrt(bn.running_var + bn.eps)).detach()
    return (c.weight.detach() * s[:, None, None]).numpy(), (bn.bias.detach() - bn.running_mean * s).numpy()


def layers(net):
    b = net.body
    L = [("conv0", *fold(b[0]))]
    for i in (1, 2, 3):
        L.append((f"dw{i}", *fold(b[i][0]))); L.append((f"pw{i}", *fold(b[i][1])))
    fc1, fc2 = net.fc1, net.fc2
    L.append(("fc1", fc1.weight.detach().numpy(), fc1.bias.detach().numpy()))
    L.append(("fc2", fc2.weight.detach().numpy(), fc2.bias.detach().numpy()))
    return L


# ------------------------------------------------ numpy mirror of fall_cnn.c
def ref_front(w):
    a, g = w[:, :3].astype(np.float32), w[:, 3:].astype(np.float32)
    u = a[:35].mean(0); u = u / (np.sqrt((u * u).sum()) + 1e-6)
    an = np.sqrt((a * a).sum(1)); av = a @ u; ah = np.sqrt(np.maximum(0, (a * a).sum(1) - av * av))
    gv = g @ u; gh = np.sqrt(np.maximum(0, (g * g).sum(1) - gv * gv))
    return np.stack([an - 1, av - 1, ah, av / (an + 1e-6), np.abs(gv) / 200, gh / 200]).astype(np.float32)


def ref_conv(x, W, b, stride, groups):
    C, L = x.shape; O, Ig, K = W.shape; Lo = (L + 2 * (K // 2) - K) // stride + 1; y = np.zeros((O, Lo), np.float32)
    per = O // groups
    for o in range(O):
        g = o // per
        for t in range(Lo):
            acc = b[o]
            for i in range(Ig):
                for k in range(K):
                    p = t * stride + k - K // 2
                    if 0 <= p < L: acc += W[o, i, k] * x[g * Ig + i, p]
            y[o, t] = max(acc, 0.0)
    return y


def ref_physics(w):
    a, g = w[:, :3].astype(np.float32), w[:, 3:].astype(np.float32)
    u = a[:35].mean(0); u = u / (np.sqrt((u * u).sum()) + 1e-6)
    p = a[100:].mean(0); p = p / (np.sqrt((p * p).sum()) + 1e-6)
    an, gn = np.sqrt((a * a).sum(1)), np.sqrt((g * g).sum(1))
    return np.array([(u * p).sum(), an[100:].std(ddof=1) * 5, gn[100:].mean() / 200, gn[40:100].max() / 200, an[20:50].min(), an[0:35].std(ddof=1) * 5], np.float32)


def ref_forward(L, w, phys=False):
    x = ref_front(w); d = dict((n, (W, b)) for n, W, b in L)
    x = ref_conv(x, *d["conv0"], 2, 1)
    for i in (1, 2, 3):
        x = ref_conv(x, *d[f"dw{i}"], 2, x.shape[0]); x = ref_conv(x, *d[f"pw{i}"], 1, 1)
    v = x.reshape(-1)
    if phys: v = np.concatenate([v, ref_physics(w)])
    h = np.maximum(d["fc1"][0] @ v + d["fc1"][1], 0)
    z = float(d["fc2"][0] @ h + d["fc2"][1]); return 1 / (1 + np.exp(-z))


def carr(name, a):
    flat = ", ".join(f"{v:.8e}f" for v in np.asarray(a, np.float32).ravel())
    return f"static const float {name}[{a.size}] = {{{flat}}};\n"


def export(net, thr, test_window, path=OUT):
    net = net.cpu().eval(); L = layers(net)
    with torch.no_grad(): p_torch = float(torch.sigmoid(net(torch.from_numpy(test_window[None]))))
    p_ref = ref_forward(L, test_window, net.phys)
    assert abs(p_torch - p_ref) < 1e-4, (p_torch, p_ref)
    with open(os.path.join(path, "fall_cnn_weights.h"), "w") as f:
        f.write("// Auto-generated by export_c.py - TinyFallNet weights (BatchNorm folded). Do not edit.\n#pragma once\n")
        f.write(f"#define FALL_CNN_THRESHOLD {thr:.6f}f\n#define FALL_CNN_PHYS {int(net.phys)}\n")
        for n, W, b in L:
            f.write(carr(f"{n.upper()}_W", W)); f.write(carr(f"{n.upper()}_B", b))
        f.write(carr("SELFTEST_WINDOW", test_window)); f.write(f"#define SELFTEST_EXPECTED {p_torch:.6f}f\n")
    n_par = sum(W.size + b.size for _, W, b in L)
    print(f"exported {n_par} float params ({n_par * 4 / 1024:.1f} KB), torch {p_torch:.6f} vs C-mirror {p_ref:.6f}")
    return p_torch
